# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "k8s-control-plane" => {"memory" => "2048", "cpu" => "2", "ip" => "110", "image" => "ubuntu/jammy64"},
  "k8s-node-01"       => {"memory" => "1024", "cpu" => "2", "ip" => "120", "image" => "ubuntu/jammy64"},
  "k8s-node-02"       => {"memory" => "1024", "cpu" => "2", "ip" => "130", "image" => "ubuntu/jammy64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.box_version = "20241002.0.0"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Cluster-K8S"]
      end
      machine.vm.provision "shell", path: "files/provision.sh"
      machine.vm.provision "shell", path: "files/k8s-common.sh"
      machine.vm.provision "shell", inline: "sudo hostnamectl hostname #{name}"
    end
  end
end